### ISSUE TITLE
Solicitud de cooperación

### ISSUE THREAD

**Issue by SHIG-ops** [gabrielizalo/calculo-digito-de-verificacion-dian#1]
Hola,
Estamos trabajando en la implementación de la Factura Electrónica con un cliente colombiano y necesitamos ayuda para conectarnos con la DIAN, por lo que decidimos contactarlo con la esperanza de que nos pueda ayudar con su valiosa experiencia.
En este momento, nuestro equipo de desarrollo está trabajando en la solución, pero necesitamos a alguien que pueda ayudarnos a conectarnos con las autoridades tributarias colombianas (DIAN) al proporcionar entradas locales específicas. Esto tomaría aproximadamente 3-4 horas de su tiempo por semana, dependiendo de la fase de integración. 
Por supuesto, se le pagará por el tiempo invertido.

Háganos saber si está interesado en la cooperación para que podamos acordar los términos.

Gracias y saludos,
Sergio

**Comment by gabrielizalo** [comment]
Hola Sergio. Claro. Si puedo ayudar con gusto.
Contactame por Linkedin: https://www.linkedin.com/in/gabrielizalo/
Saludos

**Comment by giovannireyestolentino-cloud** [comment]
Muy sencillo
